name: Hello Devops

on:
  push:

jobs:
  hello:
    runs-on: windows-latest

    steps:
      - name: Welcome Message
        run: echo "Hello from Merwin J"

      - name: Show Date
        run: Get-Date

      - name: Show User
        run: whoami